### ISSUE TITLE
Sumo Gui

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11379]
Hello,

I have few issues with Sumo-GUI 

1-) Although there is an emergency vehicle waiting in the queue, the waiting time of the emergency vehicle is not counted in game mode.

![1A4F67D0-617F-4EDD-8C0A-756B25F7A0E2](https://user-images.githubusercontent.com/82845085/185260975-e2132a51-5b66-471c-8cbf-e9dd89bce8da.png)

![882E5CAC-E560-4F4A-A6BA-D2A1C7F073C5](https://user-images.githubusercontent.com/82845085/185260990-110ef644-3528-4268-becd-51d5e4d93b34.png)

2-) Although the color of motorcycle is green, in sumo gui, the color of motorcycle is yellow

![E2129FE4-4EDD-4898-847F-8B84546B02B3](https://user-images.githubusercontent.com/82845085/185261247-9084e74a-5942-4587-9dd8-da2656a11cd4.png)

![7CEBA101-2F49-4FB6-8A34-F4AF1591A478](https://user-images.githubusercontent.com/82845085/185261398-89daa6e8-950b-45ee-9af7-e85628203bca.png)

Sumo-Gui ==>

![C759E22F-C14F-4BCA-8674-CCBB39397619](https://user-images.githubusercontent.com/82845085/185261417-a7af2576-1647-4fad-979c-604cb4d66130.png)

3-) Direction signs are located on the back of the detector but I want them as front element. Is there have any way to make direction signs as front element? 

![CBDCD6F2-DFE3-48A6-9A81-AF0782165B74](https://user-images.githubusercontent.com/82845085/185262873-3407432c-0563-4250-8541-3fd3d8f4c4a2.png)

(By the way, I know there is have a option to make road as front element but I just want direction signs as front element not whole road)

![E507303D-6BA8-440B-88F2-1A3DCCD140AE](https://user-images.githubusercontent.com/82845085/185262902-9b95ae54-b616-453a-8063-5d1d2c9102bf.png)

Thanks

**Comment by namdre** [comment]
1. fixed in ca80f8f
2. most likely you picked a color scheme that doesn't go by the vehicle color, try scheme *given vehicle color*
3. #11380, #11381

**Comment by erev-84** [comment]
Hello @namdre,

First of all thank you very much for the quick reply

1-) 

Where is the GUIApplicationWindow.cpp? I could not find the path to update it.

I don't have the directory below 

sumo/src/gui/GUIApplicationWindow.cpp

![image](https://user-images.githubusercontent.com/82845085/185413948-1032ff9f-4a75-42cc-9437-2e1af954442c.png)

Do I need to download the following zip file for that?

![image](https://user-images.githubusercontent.com/82845085/185414175-f5630d50-80cc-4878-b671-639b807138c0.png)

2-) Could you check the attached screen recording please?
[Motorcycle_Color.zip](https://github.com/eclipse/sumo/files/9374557/Motorcycle_Color.zip)

3-) As far as I understand I need to update the following ".cpp" files but I could not find them too
![image](https://user-images.githubusercontent.com/82845085/185417306-ca7cc729-b655-4ae2-86f1-bdac32eceb26.png)

As can be seen from the directory below I don't have src folder

![image](https://user-images.githubusercontent.com/82845085/185417465-2272dcd6-96e4-42a7-8197-cffeb5848538.png)

**Comment by namdre** [comment]
the recommended way to upgrade is to download the pre-built dev-version here: https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots

**Comment by erev-84** [comment]
I downloaded the zip file from the link you gave, then unzip the folder and transferred the files to the main directory where sumo is located, as seen in the screenshot below  (copy and paste-replace), but nothing changed. The 1st and 3rd problems still exist. is there something i did wrong? Also, for the second problem, I attached a screen recording in my last message, could you have the opportunity to check the screen recording?

![image](https://user-images.githubusercontent.com/82845085/185493282-6066d882-665f-434e-93a7-a10c54e00a45.png)

**Comment by erev-84** [comment]
Hello @namdre ,

The third problem I mentioned above is solved by the update but first issue still not solved. I updated my files by using updateDailyVersion.py script and I am using the new version of src/gui/GUIApplicationWindow.cpp but still although there is an emergency vehicle waiting in the queue, the waiting time of the emergency vehicle is not counted in game mode.

![image](https://user-images.githubusercontent.com/82845085/186162927-363603cf-9284-43d5-a9a3-42ea76999a23.png)
![image](https://user-images.githubusercontent.com/82845085/186164006-4dab1607-a596-4ef2-b917-823d4b43c5d1.png)
![image](https://user-images.githubusercontent.com/82845085/186164661-5bc551ae-93bc-4075-9a4d-e75bd8b800b8.png)

**Comment by namdre** [comment]
You screenshot does not show the updated version of the file which should instead look like this:
https://github.com/eclipse/sumo/blob/60ca4fee88d1795dd0b998333456bebbea1f8eaf/src/gui/GUIApplicationWindow.cpp#L1879-L1880
