### ISSUE TITLE
Left turn vehicles waiting for right turn

### ISSUE THREAD

**Issue by urielka** [eclipse/sumo#6884]
**Issue:**
Vehicles turning left on a protected phase will stop if the opposing direction has cars turning right

**See picture:**
![Screenshot from 2020-04-13 11-27-14-desc](https://user-images.githubusercontent.com/30956/79106238-c8689280-7d7a-11ea-9e02-f5a59a91ed18.png)
**Video (phenomena in 00:10):**
https://drive.google.com/file/d/1EachMrNfPP-I2PW5VzcfztyE9gP2Sb3F/view?usp=sharing

**Version:** 0.32.0 (I will upgrade if this is fixed in a newer version)
**Maybe related:** https://github.com/eclipse/sumo/issues/1698

**Config files:**
[intersection_config.zip](https://github.com/eclipse/sumo/files/4468740/intersection_config.zip)

**Comment by namdre** [comment]
This is fixed in a later version. I recommend reprocessing the network as well (loading and saving in netedit is sufficient).

**Comment by urielka** [comment]
@namdre Thank you for validating this.
Is Traci compatible between 0.32.0 to 1.5? is it a big effort to migrate between the versions?

**Comment by namdre** [comment]
@urielka TraCI must be updated when upgrading from 0.32.0. (if you uninstall 0.32.0 and install 1.5 you're almost done). Your own traci scripts can be kept mostly as they are. The major difference is that all time values are in seconds rather than milliseconds from 1.0 onward. For a list of changes see https://sumo.dlr.de/docs/ChangeLog.html#other_8

**Comment by urielka** [comment]
Hi @namdre 
It seems this issue is not 100% fixed in 1.5.0, while it solved it from that issue another similar issue happens with vehicles coming from the north turning right vs vehicles turning left from the south.


Image of the issue (vehicles are generated only from those directions)
![Screenshot from 2020-05-19 13-42-34](https://user-images.githubusercontent.com/30956/82317339-c081bb00-99d6-11ea-8787-a097b088d70f.png)

See attached the net file (saved under netedit 1.5.0 added txt for github):
[test_net_xml.txt](https://github.com/eclipse/sumo/files/4649859/test_net_xml.txt)

Video:
https://drive.google.com/file/d/1Felod_ItRM4eOCP7pG-VOp1Ism1iynwC/view?usp=sharing

**Comment by namdre** [comment]
I can confirm that there is an issue with 1.5.0. However, with version 1.6.0 I am observing the intended behavior: on green minor ('g') the left-turning vehicles yield and on green major ('G') they take precedence over the right-turning stream.

**Comment by urielka** [comment]
Is it related to this bug fix: https://github.com/eclipse/sumo/issues/6068

**Comment by namdre** [comment]
Yes. I think this is the crucial difference between 1.5.0 and 1.6.0 in regard to your issue.

**Comment by urielka** [comment]
@namdre
In green minor there is no conflict between the right turning vehicles and left turning vehicles so why they should yield? they are also on different internal lanes, no?

**Comment by namdre** [comment]
The current behavior reflects strict adherence to the traffic laws in Germany. The right turning traffic generally has free choice of lane (regardless of lane markings) and the left turning traffic has to yield.

In Practice, drivers may deviate from this behavior and of course, it could be complete safe in SUMO when the available target lanes for turning right are completely  separate from the target lanes for turning left from the opposite direction.

What jurisdiction are you simulating? Can you point to a document of traffic law that describes a different rule for how the left-turn/right-turn conflict on a multi-lane road is resolved?

If a different rule is law/common practice somewhere I would add this to the list of enhancements requests.

**Comment by urielka** [comment]
@namdre 
I am simulating in the US with permissive (minor green)-protected(major green).

The problem we are seeing is that vehicles are stuck in the middle of the intersection because the right turn vehicles stops them even when they turn on red, now with the upgrade (need to validate this) it will only happen when they have a green light.

Now when vehicles get stuck because of right-on-red turning then we serve the east-west left turning and then we have a deadlock in the intersection.

**Comment by namdre** [comment]
If you can provide a scenario which manifests a deadlock in 1.6.0 or later then I'll take a look.
By default, the east-west vehicles should let the stuck left-turners clear the intersection. 

Usually, there should be an in-between period between the phase where left-turns can enter the junction and east-west traffic can enter the junction. Possibly an protected green period but at least a yellow/allred period that allows vehicles on the junction to clear. 
Simulation of right-on-red junctions are less common so there might still be an issue there (i.e. right-on-red traffic continuing to block traffic even in the aforementioned yellow/allred clearance period).

**Comment by urielka** [comment]
OK upgraded to 1.6.0, it is still not perfect, do I need to reprocess the network?

Left turn vs right turn, you see that sometimes vehicles wait for right on red vehicles, but they also get inside "gaps" or when it moves from green to red so it is a bit better:
https://drive.google.com/file/d/1VUOQPRgGFeVuvI1oRqJAGMDgkufnIA78/view?usp=sharing

Left turn vs right turn vs left turn from east-west, you can see that there times where the east-west, you can see cases where vehicles turning to the east from south block a bit the vehicles turning to the north from the east:
https://drive.google.com/file/d/1VP1pyWixx3jKQTCTceemMjvy3udyI56P/view?usp=sharing

**Comment by urielka** [comment]
@namdre can we change this in the network itself?

**Comment by namdre** [comment]
I would recommend setting the junction type to "traffic_light_right_on_red" and to define a phase where left turn traffic can clear the intersection:
- a phase where the left turn has exclusive right of way (green major)
- a phase where all sides have red 
Either one of these should fix your issue.

Note, In your case, where the right turn is uncontrolled, the right-turning traffic always has to brake even when there is a green light for the straight direction. With traffic_light_right_on_red, the right turn either has a green light or it has to stop and can then turn (this is a common rule in many jurisdictions).

There is one thing that cannot (yet) be changed in the network:
A option to make left and right turn compatible when they target different lanes (I would prefer to get confirmation that this is common behavior in some country before implementing it).
