### ISSUE TITLE
DFROUTER Flow file corrupt Error while flow file is fine 

### ISSUE THREAD

**Issue by Smiley4ever21** [eclipse/sumo#6931]
Hi, I am using DFROUTER to generate traffic in SUMO 1.3.1.
My command is:
 dfrouter --net-file duisburgring.net.xml --detector-files duisburgring.loopcr.xml --measure-files flow605.csv --routes-output duisburgring.rou.xml --emitters-output duisburgvehicle.xml

But I receive Error: 
Error: The detector-flow-file 'flow605.csv' is corrupt;
 The following values must be supplied : 'Detector', 'Time', 'qPKW'
 The according column names must be given in the first line of the file.
Quitting (on error).

My flow605.csv has already have the first line as: Detector;Time;qPKW;qLKW;vPKW;vLKW
second line: 605-D1;443;60;0;72.6;72.6
third line: 605-D1;448;60;0;72.6;72.6
...

Could you tell me why I still receive this Error? Thank you!

**Comment by behrisch** [comment]
I just tried the same input here and it worked. Can you include your complete inputs (with network and detector definitions)?
PS: It is a little strange to have a speed for LKW when there are none but this should not trigger an error.

**Comment by Smiley4ever21** [comment]
Hi,
all the files are in attachment, the command I use is:

dfrouter --net-file duisburgring.net.xml --detector-files
duisburgring.loops.xml --measure-files flow605.csv --routes-output
duisburgring.rou.xml --emitters-output duisburgvehicle.xml

Michael Behrisch <notifications@github.com> 于2020年4月23日周四 下午6:40写道：

**Comment by behrisch** [comment]
There seems to be no attachment, maybe you need it to add it directly (and not via email).

**Comment by Smiley4ever21** [comment]
[detector.zip](https://github.com/eclipse/sumo/files/4524003/detector.zip)
Can the attachment be seen now?

**Comment by behrisch** [comment]
Your input file contained a so called byte order marker (three bytes at the beginning which mark that the input file is UTF8) and is silently hidden by most editors and viewers. Still it confused dfrouter but this is fixed now.

**Comment by Smiley4ever21** [comment]
Should I delete sentence <?xml version="1.0" encoding="UTF-8"?> in the detector definition file? Or should I delete the LKW information in the csv file? How can I get the route file with vehicles?

**Comment by behrisch** [comment]
You need to find an editor which shows you that the first three bytes of your csv file are not "Det" and then delete them. Copying the contents to a new file may help as well.

**Comment by Smiley4ever21** [comment]
[detector.zip](https://github.com/eclipse/sumo/files/4527630/detector.zip)
I've deleted the three bytes of the csv file, but Ithe error is still like:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python38\lib\xml\sax\expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
xml.parsers.expat.ExpatError: mismatched tag: line 154, column 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\sumo-1.3.1\tools\detector\flowrouter.py", line 986, in <module>
    sources, sinks = reader.readDetectors(options.detfile)
  File "C:\Users\Admin\Desktop\sumo-1.3.1\tools\detector\flowrouter.py", line 842, in readDetectors
    self._detReader = detector.DetectorReader(detFile, self._lane2edge)
  File "C:\Users\Admin\Desktop\sumo-1.3.1\tools\detector\detector.py", line 161, in __init__
    parser.parse(detFile)
  File "C:\Program Files\Python\Python38\lib\xml\sax\expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "C:\Program Files\Python\Python38\lib\xml\sax\xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "C:\Program Files\Python\Python38\lib\xml\sax\expatreader.py", line 221, in feed
    self._err_handler.fatalError(exc)
  File "C:\Program Files\Python\Python38\lib\xml\sax\handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: duisburgring.loops.xml:154:2: mismatched tag

The attachment is the files I use, is there something wrong with the mesure file "duisburgring.loops.xml"? Thank you.

**Comment by behrisch** [comment]
Yes your loops file has a syntax error in line 84. The slash needs to be outside the quotes

**Comment by Smiley4ever21** [comment]
Thanks a lot!!!

**Comment by Smiley4ever21** [comment]
Hi, sorry to disturb you again. Thanks to your guidence, I have emitters-output files with vehicles now, but it cannot be used in simulation, because there are not exactly edges but only trips with start and end point.

I tried to include it into the sumocfg file and use it in sumo-gui.exe, but it cannot be used by that way.
Then I tried to use duarouter to generate these edges, but failed.
Could you please tell me, how could I use the "route" file generated from the emitters in simulation? Thank you.

**Comment by behrisch** [comment]
Have you read this one: https://sumo.dlr.de/docs/Demand/Routes_from_Observation_Points.html#how_to_include_the_files?

**Comment by Smiley4ever21** [comment]
Thank you.
[DFRouter problem.zip](https://github.com/eclipse/sumo/files/4533669/DFRouter.problem.zip)
I enconter a speed conflict in simulation. The simulation files are in attachment.
The error information in SUMO-gui.exe is:
Error: Vehicle '605-D1.8347' will not be able to depart using the given velocity (slow lane ahead)!
But the depart speed of the vehicle is 22.39, and the allowed speed of the lane I have already changed to 27.79. The speed limit should be enough to let the vehicle start. 
Could you please tell me why the vehicle can still not depart and how can I fix it? Thank you.
